import test from 'node:test';
import assert from 'node:assert/strict';
import {scanSource,shouldScanPath} from '../src/core.mjs';
test('normal adaptive UI and orientation declarations are not defects',()=>{
 assert.equal(scanSource('App.swift',`Color.blue.ignoresSafeArea()
 Text("x").frame(width: 44, height: 44)
 Text("x").frame(width: 800)
 navigationController.setNavigationBarHidden(false, animated: true)
 var orientation: UIInterfaceOrientation
 NavigationSplitView { List {} } detail: { Text("x") }
 `).length,0);
});
test('Apple doubled inset example and reversed multiplication are caught',()=>{
 for(const value of ['view.safeAreaInsets.left * 2','2 * view.safeAreaInsets.right','view.safeAreaInsets.left + view.safeAreaInsets.left']) {
 assert.equal(scanSource('App.swift',`let width = view.bounds.width - ${value}`)[0]?.rule,'symmetric-safe-area-assumption');
 }
 assert.equal(scanSource('App.swift','let width = view.bounds.width - view.safeAreaInsets.left - view.safeAreaInsets.right').length,0);
});
test('nested comments, raw/multiline strings and generated sources are skipped',()=>{
 assert.equal(scanSource('App.swift','/* a /* UIScreen.main */ */\nlet s = #"UIScreen.main"#\nlet x = """\nUIScreen.main\n"""').length,0);
 assert.equal(scanSource('Generated.swift','// Generated by SwiftGen. Do not edit.\nlet a = UIScreen.main').length,0);
 for(const p of ['Tests/Foo.swift','Vendor/Foo.swift','Generated/Foo.swift','Foo.generated.swift','Console-tvos.swift']) assert.equal(shouldScanPath(p),false);
});
